web:
  build: .
  command: bundle exec rails s -p 3000 -b '0.0.0.0' -P tmp/pids/server1.pid
  volumes:
    - .:/myapp
  ports:
    - "80:3000"
  links:
    - db
db:
  image: postgres
  ports:
    - "5432"



